sudo: required
language: java
jdk:
- oraclejdk8
dist: trusty
branches:
  only:
  - master
  - develop
before_install:
- mkdir -p ~/.m2; wget -q -O ~/.m2/settings.xml https://raw.githubusercontent.com/nbnuk/travis-build-configuration/master/travis_maven_settings.xml
- sudo mkdir -p /data/lucene; sudo wget -O /data/lucene/namematching-20190213.tgz
  https://biocache.ala.org.au/archives/nameindexes/20190213/namematching-20190213.tgz
- cd /data/lucene
- sudo tar zxvf namematching-20190213.tgz
- sudo ln -s namematching-20190213 namematching
- ls -laF
- cd $TRAVIS_BUILD_DIR

script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && mvn clean install deploy -Dmaven.test.skip=true -Ptravis || mvn clean install -Dmaven.test.skip=true -Ptravis'
env:
  global:
  - secure: zr9+T3cCIGEjPY6nCukDr0u+n2n7dYCKecZlKflYLkvLk0QODhKbffPLaH9iNd8WiWjTRO0zIo4hi6oJ7iua2GaOoULqcPuKXIoLC6Sr4DTB/4ZOv9OmLwzRyGysr7Je/5ByDhnloTQ/FHenFrdrmV2mXf0pt5ogjyVgip2ErQmteLenPV12860Zbz4KTvRJK/ogFGah45OaKWqASkmo9mt9x1UJD12aXmxjKcf6mwmkzSiC0wq1cfFqF2VtlKIx3c0K4l8ruun8cl2VYV5oQFPXwcNP3eHP/WiyyFcGHGcX4r/6jCa7AJKcY85eqr5EqP/1V2PXQniy9JUIlqC4EW1Wi1uAwvzfuwPk24ejBo02xhfG3snT5pbW5uf9w8gp4aY3B1wh+veNz1p6cyivDTiFepJDzIIDCX1R8JqTCbbiSJEBODXBdpPjPjb2kU3jUmmqYKpSoW9gxKIntRVXvYUgc7jQLKOAPrasOk/D/1RBu9Pn8vGlHkXvkIpzIVIQGS+W1qxD8VDh5qCJZ9Egz4C40OExWfBbdNnYTO3hN4OH4hJFEjRj02Z7jYJKYNbHSNGeTYHP5Pxb8HQyLDcr/WQlLoiodhKMD6yXiwNEHCr/0Q61toCa4mMtNgjL3W8OQkByCDvd4ib7cEeTY5Yj0p0i8XmiLQAy1LH1au0V5hY=
  - secure: PBl0EsqKnuccVBrpT0csuzntcKlZ1LR8LKovR7im7cX8VbOrOdXskKTksK/hmf9NE9AB9zir2If3+4osZdH8N7qpp/5Od1MvJudCrVb7trvelolDjTiFrzVPXtKf9pQdIZRORMJ/SjnXLBvf2DgjrbaH85JV/yGpPiylnghLfOjWT303HJ/+/iZ2UIKWaMQlq4NQNcDB8zRxKG3SMjysh0gaDr/L+3Qkra8kGRapS0/Ppohu7n0w2lIx0rV+2784L5/BIGOQkkGgK4kDPMxE5fWB5EISM0DeMRoepe+HdBWwzQe6EzHP3nqgIAMl4VaOtliIaFBspwM90AoT5ZKNCNJrrygPIqFQfQug7ffHtfB7QQ8IiHT/hIGTMsJeuOXTKRYOkNJO1oRSPHqc00u9/FcEJoqwZvn2V2ft+60GeufPcsVK7kA5CIMpnWZ8kJMB+aoYB3WKld3DCZ8GDwnp86xHYDzAmQtAPWR//3Gkk6lArvgy3le3uDEnsgs5uTdtboLp4/epEETI8jG2kGMLIjyOt99KUOV6ouBl88OmbOTgIYkiuzdo2q6TUcAJVB5zypeHMeg909EeKrERdtjJAICoRijhTBBSVmaJdFdNreSO28cbRVknkCnMkLYN72+7nlJkD8tyClRrgd26kpO+ZKN4N5cDSeBwSlauafwqUQE=
